services:
  ezpublish.security.form_login_guard_authenticator:
    class: CodeRhapsodie\EzAuthenticationBundle\Security\Guard\Authenticator\EzFormLoginAuthenticator
    arguments:
      - "@ezpublish.api.repository"
      - "/login"
      - "/"