services:
  CodeRhapsodie\EzAuthenticationBundle\Security\EzLoginAuthenticator:
    class: CodeRhapsodie\EzAuthenticationBundle\Security\EzLoginAuthenticator
    arguments:
      - "@ezpublish.api.repository"